{% set name = "grime-ai-post" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    path: .

build:
  number: 2
  script:
    - copy %RECIPE_DIR%\download-sam2-checkpoints.bat %PREFIX%  # [win]
    - copy %RECIPE_DIR%\download-sam2-checkpoints.py %PREFIX%  # [win]
    - cp -v ${RECIPE_DIR}/download-sam2-checkpoints.py ${PREFIX}/bin/download-sam2-checkpoints # [unix]
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin="x") }}

requirements:
  host:
    - python
  run:
    - python

test:
  commands:
    - if not exist %PREFIX%\download-sam2-checkpoints.bat exit 1 # [win]
    - test -f ${PREFIX}/bin/download-sam2-checkpoints # [unix]

about:
  home: https://gaugecam.org/grime-ai-details/
  dev_url: https://github.com/JohnStranzl/GRIME-AI/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "GRIME-AI is a tool that facilitates the entire data science workflow for ground-based time-lapse imagery, from data acquisition to model deployment."
