# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\johns\pycharmprojects\neonAI\QDialog_ExtractCOCOMasks.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(851, 222)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        Dialog.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(373, 180, 80, 40))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.lineEdit_COCOAnnotationFile = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_COCOAnnotationFile.setGeometry(QtCore.QRect(27, 51, 710, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lineEdit_COCOAnnotationFile.setFont(font)
        self.lineEdit_COCOAnnotationFile.setObjectName("lineEdit_COCOAnnotationFile")
        self.pushButton_BrowseAnnotationImages = QtWidgets.QPushButton(Dialog)
        self.pushButton_BrowseAnnotationImages.setGeometry(QtCore.QRect(740, 135, 80, 20))
        self.pushButton_BrowseAnnotationImages.setObjectName("pushButton_BrowseAnnotationImages")
        self.lineEdit_AnnotationImagesFolder = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_AnnotationImagesFolder.setGeometry(QtCore.QRect(27, 130, 710, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lineEdit_AnnotationImagesFolder.setFont(font)
        self.lineEdit_AnnotationImagesFolder.setObjectName("lineEdit_AnnotationImagesFolder")
        self.pushButton_BrowseAnnotationFile = QtWidgets.QPushButton(Dialog)
        self.pushButton_BrowseAnnotationFile.setGeometry(QtCore.QRect(740, 56, 80, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_BrowseAnnotationFile.setFont(font)
        self.pushButton_BrowseAnnotationFile.setObjectName("pushButton_BrowseAnnotationFile")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(17, 90, 811, 21))
        self.line.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.line.setFont(font)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(3)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(30, 30, 180, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(30, 110, 180, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.buttonBox_ok_cancel = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox_ok_cancel.setGeometry(QtCore.QRect(500, 180, 167, 25))
        self.buttonBox_ok_cancel.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_ok_cancel.setObjectName("buttonBox_ok_cancel")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Image Utilities"))
        self.pushButton_BrowseAnnotationImages.setText(_translate("Dialog", "Browse"))
        self.lineEdit_AnnotationImagesFolder.setToolTip(_translate("Dialog", "This field is pre-populated and cannot be changed at this time."))
        self.pushButton_BrowseAnnotationFile.setText(_translate("Dialog", "Browse"))
        self.label_10.setText(_translate("Dialog", "COCO Annotation File"))
        self.label_8.setText(_translate("Dialog", "Annotation Images"))
