{% set name = "grime-ai" %}
{% set version = "1.1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    path: /repo
  #git_url: https://github.com/JohnStranzl/GRIME-AI.git
  #git_rev: main

build:
  number: 12
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - mkdir -p "{{ PREFIX }}/Menu"
    - sed "s/__PKG_VERSION__/${PKG_VERSION}/g" "${RECIPE_DIR}/grimeai-menu.json" > "${PREFIX}/Menu/${PKG_NAME}_menu.json"
    - cp -v "src/GRIME_AI/resources/app_icons/GRIME-AI Logo.ico" ${PREFIX}/Menu/grimeai.ico
    - cp -v "src/SAGE/resources/sage_logo.ico" ${PREFIX}/Menu/sage.ico

  run_exports:
    - {{ pin_subpackage(name|lower, max_pin="x") }}
  entry_points:
    - grime-ai = GRIME_AI.main:my_main
    - sage = SAGE.main:main

requirements:
  host:
    - python >=3.8,<4.0
    - pip
    - setuptools
  run:
    - python >=3.8,<4.0
    - bs4
    - exifreader 0.1.*
    - html5lib 1.1.*
    - hydra-core 1.3.*
    - imageio 2.36.*
    - iopath 0.1.*
    - matplotlib 3.*
    - neonutilities 1.2.*
    - numpy 1.*
    - opencv 4.*
    - openpyxl 3.1.*
    - pandas 2.1.*
    - peft 0.18.*
    - piexif 1.1.*
    - pillow 9.*
    - promptlib 1.0.*
    - pycocotools 2.0.*
    - pyqt 5.*
    - pyqtwebengine 5.*
#    - pyside6 6.*
    - pywavelets 1.8.*
    - pywin32 311  # [win]
    - requests 2.31.*
    - rpy2 3.6.*
    - sam2 1.0.*
    - scikit-image 0.24.*
    - scikit-learn 1.*
    - seaborn 0.13.*
    - segment-anything 1.0.*
    - selenium 4.*
    - supervision 0.20.*
    - pytorch 2.8.*
#    - torchaudio 2.8.*
    - torchvision >=0.22.*
    - transformers 4.57.*
    - webdriver-manager 4.0.*
    - r-base 4.4.*
    - r-neonutilities 3.*
    - grime-ai-post 1.0.1.*

test:
  commands:
    - grime-ai --help
    - sage --help

app:
  entry: grime-ai
  name: GRIME-AI
  display_name: "GRIME-AI"
  summary: "GRIME-AI is a tool that facilitates the entire data science workflow for ground-based time-lapse imagery, from data acquisition to model deployment."
  icon: "../../src/GRIME_AI/resources/splash_screens/GRIME-AI Logo.jpg"
  type: desk
  own_environment: True

about:
  home: https://gaugecam.org/grime-ai-details/
  dev_url: https://github.com/JohnStranzl/GRIME-AI/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "GRIME-AI is a tool that facilitates the entire data science workflow for ground-based time-lapse imagery, from data acquisition to model deployment."
