name: Nightly Build

on:
  schedule:
    - cron: '0 6 * * *'  # daily at 6am UTC
  workflow_dispatch:      # allows manual trigger from GitHub UI

jobs:
  nightly:
    runs-on: ubuntu-latest
    container: quay.io/condaforge/linux-anvil-cos7-x86_64
    steps:
      - name: Checkout repo
        run: |
          cd $GITHUB_WORKSPACE
          source /opt/conda/etc/profile.d/conda.sh
          conda activate base
          git clone -b $GITHUB_REF_NAME $GITHUB_SERVER_URL/$GITHUB_REPOSITORY .

      - name: Set nightly version
        run: |
          DATE=$(date +%Y%m%d)
          BASE=$(sed -n 's/.*{%.*set version.*=.*"\(.*\)".*/\1/p' recipe/grime-ai/meta.yaml)
          echo "NIGHTLY_VERSION=${BASE}.dev${DATE}" >> $GITHUB_ENV

      - name: Patch meta.yaml version
        run: |
          sed -i "s/{% set version = \".*\" %}/{% set version = \"$NIGHTLY_VERSION\" %}/" \
            recipe/grime-ai/meta.yaml

      - name: Build and upload to dev label
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          source /opt/conda/etc/profile.d/conda.sh
          conda activate base
          conda install conda-forge-pinning=2024.11.29.12.37.53 -y
          conda config --set anaconda_upload yes
          conda build -c grimelab -e /opt/conda/conda_build_config.yaml \
          --label dev --user grimelab --token $ANACONDA_API_TOKEN recipe/grime-ai
